name: tawseela
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  firebase_messaging: ^14.6.9
  firebase_storage: ^11.2.8
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  dio: ^5.3.3
  location: ^5.0.3
  google_maps_flutter: ^2.5.0
  flutter_polyline_points: ^1.0.0
  firebase_database: ^10.2.7
  rxdart: ^0.27.7
  dartz: ^0.10.1
  get_it: ^7.6.4
  geolocator: ^10.1.0
  flutter_geocoder_alternative: ^1.0.3
  shimmer_animation: ^2.1.0+1
  shared_preferences: ^2.2.2
  internet_connection_checker: ^1.0.0+1
  google_nav_bar: ^5.0.6
  flutter_geofire: ^2.0.3
  http: ^0.13.5
  smooth_star_rating_null_safety: ^1.0.4+2
  image_picker: ^1.0.4
  url_launcher: ^6.2.1
  flutter_phone_direct_caller: ^2.1.1







dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/car.jpg
    - assets/images/side_car.jpg
    - assets/images/side_car.png
    - assets/images/motor_cycle.png
    - assets/images/google_logo.png
    - assets/images/facebook_logo.png
    - assets/images/promo_logo.png
    - assets/images/logo3.png
    - assets/images/logo7.png

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

